version: "3.8"

services:
  qdrant:
    image: "qdrant/qdrant"
#    command:
#      - ./qdrant
#      - --config-path
#      - /qdrant/config/config.yaml
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
      - ./qdrant/config:/qdrant/config/
    networks:
      - backend
  api:
    build: ./api
    ports:
      - "80:80"
    environment:
      SERVER_QDRANT: qdrant
      PORT_QDRANT: 6333
      COLLECTION_NAME: songs
    depends_on:
      qdrant:
        condition: service_started
    networks:
      - backend


volumes:
  qdrant:

networks:
  backend:
    name: custom-backend
    driver: bridge
