version: "3.8"

services:
  qdrant:
    image: "qdrant/qdrant"
#    command:
#      - ./qdrant
#      - --config-path
#      - /qdrant/config/config.yaml
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
      - ./qdrant/config:/qdrant/config/

volumes:
  qdrant:
